GET http://localhost:3001/todos/?status=TO%20DO
###

GET http://localhost:3001/todos/?priority=HIGH
###
GET http://localhost:3001/todos/?priority=LOW&status=DONE
###
GET http://localhost:3001/todos/?search_q=Play
###

GET http://localhost:3001/todos/3/
###
POST http://localhost:3001/todos/

{
  "id": 10,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}
###

PUT http://localhost:3001/todos/5/
{
      "status": "DONE"
    }

###
PUT http://localhost:3001/todos/6/
{
      "priority": "HIGH"
    }
    
###
PUT http://localhost:3001/todos/9/
   {
      "todo": "Some task"
    }
    
###



DELETE http://localhost:3001/todos/10/